In [13]:
import numpy as np
from math import sqrt

In [4]:
def gen_array(lim, sizeX, sizeY):
    return np.random.randint(lim, size = (sizeX, sizeY))

A)

In [7]:
A = gen_array(10, 3, 4)
B = gen_array(10, 4, 4)
print("A: ", A, "\n", '-'*20)
print("B: ", B, "\n", '-'*20)

A:  [[2 5 9 5]
 [5 2 6 2]
 [3 6 8 5]] 
 --------------------
B:  [[9 7 1 2]
 [2 6 9 0]
 [0 7 1 5]
 [5 5 3 3]] 
 --------------------


B)


In [12]:
A = gen_array(10, 4, 4)
B = ~(A%2) + 2
print("A: ", A, "\n", '-'*20)
print("B: ", B, "\n", '-'*20)

A:  [[9 3 3 8]
 [4 9 9 2]
 [1 9 9 2]
 [6 1 3 9]] 
 --------------------
B:  [[0 0 0 1]
 [1 0 0 1]
 [0 0 0 1]
 [1 0 0 0]] 
 --------------------


C)

In [14]:
def prime(n):
    if (n%2 == 0 and n > 2) or (n < 2):
        return False
    return all(n%i for i in range(3, int(sqrt(n) + 1), 2))

In [17]:
A = gen_array(10, 5, 5)
print("A: ", A, "\n", '-'*20)
A = np.fliplr(A)
func = np.vectorize(prime)
A_temp = func(A.diagonal())
count_prime = len(np.extract(A_temp, A))
print("A flip left to right: ", A, "\n", '-'*20)
print(count_prime)

A:  [[2 4 4 9 7]
 [5 1 7 5 1]
 [9 5 7 1 0]
 [3 3 4 2 3]
 [0 2 8 0 6]] 
 --------------------
A flip left to right:  [[7 9 4 4 2]
 [1 5 7 1 5]
 [0 1 7 5 9]
 [3 2 4 3 3]
 [6 0 8 2 0]] 
 --------------------
4
